---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'


inputs:
  - name: order-mgmt-repo

outputs:
  - name: build-output

run:
  path: order-mgmt-repo/ci/tasks/build-order-mgmt.sh
