---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'


inputs:
  - name: web-store-repo

outputs:
  - name: build-output

run:
  path: web-store-repo/ci/tasks/build-artifact.sh
