---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'


inputs:
  - name: fulfillment-service-repo

outputs:
  - name: build-output

run:
  path: fulfillment-service-repo/ci/tasks/fulfillment-service/build-fulfillment-service.sh
