GIT_REPO: git@github.com:mambrose-pivotal/hybrid-demo.git
GIT_BRANCH: master
GIT_PRIVATE_KEY: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEA6NhzHZlQbBcrPcQMj2FTyN5gePorD0oOASHQLSSQCfk7ylyT
  +bFE5jIi6FBk1baPyS1NUcuIMxoLXs1k1I+3rrHHAWMVb5vMRBsr2I591uYatoTm
  kv74NgIGI83il896/x+qW8D/h8htT5JMany1lmzssSleweNHYuGSOrXYuoeETJkY
  GIVPjPrFvorLCWM9iOruYLFqLhaU5u58rwt8fWFqk0FxO4x1baRhJ6WNq1GDeyGt
  cYprrmm7hqj7qnZBLxhOietuskVmwakT6Qu9t2sf4gvhtbsScvxRnpH3jLwt9D4q
  krDnhPthC/QM00qW02e2QSA/WDZN3yW0D+do0W3JgX/PwlhZfJwHGoYQDxsmVDuK
  7LqIZXY/ErCGk2pXTPOpfdRfSzyLVnqcSSHqSrtdlHmG8KnHLaBKTBz5fQW+y4d3
  a7q0DYwEp4iLJAmyClfugAOtwlmaqMQj5GURmNdAHINHH6YkdRp/y4rNIhppQ6/Q
  GqWg06gsWpIYH6TvrwQyAcFob0de+0MTXJq4ExWka4Jz0uyc2Szi4FRsAM+p0t9D
  TbcoES3baT4Yi9ZVUYkr/JyUNkKmAmeuki4VSN1Wv+rdTyi3MrN4hqx1hL9wlnTE
  Oya3Qudb3Gj9iQnj4ft3ALkscwNTb/IgwCnBVRr8Q+DEeAsj5YcVDeEJQO0CAwEA
  AQKCAgEAv+F3Y+HvA1RIfxrrWtDS0cpn5+oIyA234rjxq/HgfUeVPRrzmqW56JVS
  bO2rWu6aKSga+pfmgm4pBpPuTrisntrD62GyzYmvWESn6krqasivJM/6jxJsi105
  oBHPdFk3u7xlkD1IlqXVZuhh7rMclXznxMsZ2l+oeVT4Q0eN9ZEttk3HLJXXS49w
  m6gWz4KnuAgaLzalEJvtUy0fNMUbbttzjywz2uXR82ut4JUuXQrMdhD3tIRkXpOl
  RMBGvF+9MckvF7sbOu+0UU07KiZRzjAKUyaFd1RVTMqfnDQfsyt0Fz2Pqdj8wXrC
  q64PT6O9DTP/XkXrzY7at1SDwUNq/PCOBocAGIRovJl1zZKU4zX28T3xsbj7SNel
  KUyXkAX69d4OhC/B4tGM+DSivDgn4LsZEGrrlLmiKhBrYurPaAm3RmXwve5xBWBU
  twholnmQ5se20EWXg4I6DcftTOrMgLtRZ8lvYCOm46c8Otarnh5Yk2oVAsxpNnob
  iXICb6KM+S8UQK2OsFYOMU5+bFWA4hdQt4JmvRY+qLuklBsMsuj5/dCx2KAdf80p
  03HBCk5dv8rSRuPwOXfyvlWIDu/ZVgqirV6eA0r1LPEP2mlWF7+lCPMGBE93YVTs
  iLcskBmIHoem/um/DO7GbkihXV8e5g7yKdfI13MO0FkAucAsmsECggEBAPuzJW0K
  iVwzqUZ2otXYAc11YW6uvDU1rOFQ4qRf0gmJ3Eu5o4W31Telu6A2U/WeYyokjowU
  4JxST+TIkYU1kCl388Kc6tNpKMqGFMSO2NofC8vhd52yblGZXDznPLMCn5DK+7he
  DPdhq6lTc6Jq7yRej1JXPmB0YvtWmeheyFaq8PjW8c0R0EpOUGZJxWlwvWMN/k7Z
  rib3OEroCdzWh1jpWYck7al+5v6c59EFWrB3hl1WUiGXeT2IenYvt8uUjXydP6jW
  5dChoKMnwren9kheO7Rjhqi9rjtvGGY93qjFj41gUxskcYLV3Zs5e46Kb3Z4bq+H
  +qjkmjsLwJ306zECggEBAOzS10YZKIZb8YmSMpDmFPp7eCedaHv4iA6zEubPMCg0
  maOZD1Vv2hON6x/RVOyR3VfK11niq7tEmoYwC6EMuY2A+t5a0IqeWpWQAEML4Tlt
  WLrUEh5SUFcGadsDd1dOiUuayuqgOCEosYNp7UAp8IOhfmySd5e5DAptvzIZFXOD
  eD7peJkvGmYgo9MpWy7O2iZnbdYQZKx801cGu1/TydHtu9SpjtpR5QvyOrST1YAZ
  YsDGGJLVlAgCtI+TrdBVxJj2elwbr4RdQr3ICMXDqKHB73kAR6H/IeSJbbVphtP2
  EFW1JvOYcGSseZOmV6xsr+jH/feWn0ayRgDPaDXKin0CggEAMyz4hhQnW4zRdRc4
  Any52RltpwB2GeeA8ArvGfa1kOTr2qWy/sQi4P6ciHWjWoRKq03lgcvY40/FGMJC
  /C+o0RWnhUE8aaGu/oaGgHR+2NKJJnoARRr7XTHuVB+78rWs1da/mXvd7Qp5yaLD
  Fxng56cmQtqkPx5K5cl0348t8pktB5tEbKqbjBAiPrnvHoIir5ovw750r02Cr5BA
  ORuRR12iq1yxyc2Yj9o9M/1/s/OJaT7c0iGnMACozZDkMMtSfSzHvb972JCURbgW
  2hqXc51dTE8UGQj//OuYrWkU9YG9r0QPgaxGPBDZzu7AFXpGMXNJJf1i1KYuSaUZ
  E8SxcQKCAQBW0tm/xlt4Ht9Hu4S0YNYSGxArHed/g9eF5Bsq6YzTQK2PL/9SKGbA
  QoiQKrPC45tNo30eZB7n0jgAuD6bNcoVWdMfkBXirDmzmY6vBfz1i+Q64qMd4Lm5
  ng1TEUtAg/eL810vdbv+VCf4cO5dVsLpz1xFO9GCm4IRlLjDCjU2G14LWpcvOfio
  tpC5SvE2EPojmEnJcEsofb8RqdMqR8A3KbxyNBO+cMXTgmQJbiWZCDWPTVEXDBxw
  b2V5OgBAYCFqnvqvKCtKENL2Nw8YSipZ23sLVpHsj1gCrGu/Vcfrj8vfUEHOjvWt
  wxnzismb2mEHq8KtcdhFF/jYNTIUfoQVAoIBABT0Wus3Ulx7RLtbCQ9cCJqRusK2
  RJ30oA98gAOZ6FQ5hVBax+d4c28sUGUzKfTEfxXdu9exCFc4R/k2wlS0XpOXCWuB
  5vu+ZwuKaevr+MbFTywwi11747vJbChGGZjTPFltzbxedJqQo2DGQBu+Z97iOfX4
  XM6NvR6ENVw43j4yuX6fbXqoHUEDo6WspCSfc3hHR6lY0jOACo5I40JnIukkKKn5
  o/qaSsemajW4Mow8G28DlCCtQeDDd4y2xJweTowcz0obRn2kML1wKFA9NpB80Bdh
  1YJfiLvjYYCzpdAbiY8nc6DS7fOd6iyfFSWsNHcV1Tu5DZALCmzN3rRrGLE=
  -----END RSA PRIVATE KEY-----
PWS_API: https://api.run.pivotal.io
PWS_USER: cstewart@pivotal.io
PWS_PASS: 674621cW$
PWS_ORG: Channel
PWS_SPACE: development
GCP_API: https://api.sys.pcf.pivotalcloud.ninja
GCP_USER: cstewart@pivotal.io
GCP_PASS: 674621cW$
GCP_ORG: cfsummit
GCP_SPACE: fulfillment


