---
jobs:
  - name: deploy-app
    plan:
    - get: git-repo
      trigger: true
    - task: build-artifact
      file: git-repo/ci/tasks/build-artifact.yml
    - put: deploy-to-azure
      params:
        manifest: git-repo/web-store/manifest.yml
        path: build-output/web-store-0.0.1-SNAPSHOT.jar
    # - put: deploy-to-gcp
    #   params:
    #     manifest: git-repo/manifest.yml
    #     path: build-output/concourse-app-0.0.1-SNAPSHOT.jar

resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    paths:
      - web-store/*
    branch: {{GIT_BRANCH}}
    private_key: {{GIT_PRIVATE_KEY}}

- name: deploy-to-azure
  type: cf
  source:
    api: {{AZURE_API}}
    username: {{AZURE_USER}}
    password: {{AZURE_PASS}}
    organization: {{AZURE_ORG}}
    space: {{AZURE_SPACE}}
    skip_cert_check: true
#
# - name: deploy-to-gcp
#   type: cf
#   source:
#     api: {{GCP_API}}
#     username: {{GCP_USER}}
#     password: {{GCP_PASS}}
#     organization: {{GCP_ORG}}
#     space: {{GCP_SPACE}}
#     skip_cert_check: true
